name: sample

description: sample

inputs:
  message:
    description: input message
    required: false
  value-with-default:
    description: default value test
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Echo env
      run: |
        echo "${{ env.FOO }}"
      shell: bash
    - name: Echo inputs
      run: |
        echo '${{ toJson(inputs) }}'
      shell: bash
    - name: Expression
      env:
        DOUBLE_QUOTE: "${{ inputs.value-with-default }}" # => 'true'
        SINGLE_QUOTE: '${{ inputs.value-with-default }}' # => 'true'
        NO_QUOTE: ${{ inputs.value-with-default }} # => 'true'
        NO_BRACKET: inputs.value-with-default # => 'inputs.value-with-default'
      run: |
        echo '${{ env.DOUBLE_QUOTE }}'
        echo '${{ env.SINGLE_QUOTE }}'
        echo '${{ env.NO_QUOTE }}'
        echo '${{ env.NO_BRACKET }}'
      shell: bash
