name: playground

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      choice:
        required: true
        default: all
        type: choice
        options:
          - apple
          - banana
          - orange
      str:
        required: false
        default: null
        type: string

defaults:
  run:
    shell: bash

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Octocat"
    steps:
      - name: Echo context and input
        run: |
          echo "github = ${{ toJson(github) }}"
          echo "inputs = ${{ toJson(inputs) }}"
      - name: Echo secret for test
        run: |
          echo "secret ${{ secrets.DUMMY_SECRET }}"
      - name: Echo with mask
        run: |
          echo "::add-mask::$MY_NAME"
          echo "hello, $MY_NAME"
      - name: Use env
        env:
          SOME_KEY: |-
            line 1
            line 2
        run: |
          echo "${{ toJson(env.SOME_KEY) }}"
